apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-b-20
spec:
  hosts:
  - service-b
  http:
  - route:
    - destination:
        host: service-b
        subset: v-green
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-b-20
spec:
  host: service-b
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v-green
    labels:
      version: v-green
