apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: middle
type: Opaque
data:
  username: cm9vdA==
  password: Vm54aW1aV3dFRA==
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
    version: 4.2
  name: mongo
  namespace: middle
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
    version: 4.2
  name: mongo
  namespace: middle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      version: 4.2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        version: 4.2
    spec:
      containers:
      - image: mongo:4.2
        imagePullPolicy: IfNotPresent
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-auth
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-auth
              key: password
        ports:
        - containerPort: 27017
          name: tcp
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /data/db
      volumes:
      - name: db-persistent-storage
        # Do NOT use in production.
        emptyDir: {}
