apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
    component: service
    version: "1.5.2"
spec:
  ports:
  - name: http2
    protocol: TCP
    port: 50051
  selector:
    app: service-b
    component: service
    version: "1.5.2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
    component: service
    version: "1.5.2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-b
      component: service
      version: "1.5.2"
  template:
    metadata:
      labels:
        app: service-b
        component: service
        version: "1.5.2"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-b
        image: garystafford/go-srv-b:1.5.2
        # resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: LOG_LEVEL
          value: info
        ports:
        - containerPort: 50051
        imagePullPolicy: IfNotPresent
